import 'package:ciyone_nutrimix/core/constants/app_colors.dart';
import 'package:flutter/material.dart';

List<Map<String, dynamic>> categories = [
  {
    'label': 'Sports Nutrition',
    'image': 'assets/categories/sports_nutrition.png',
    'color': AppColors.error,
  },
  {
    'label': 'Vitamins & Supplements',
    'image': 'assets/categories/vitamins&supplements.png',
    'color': AppColors.ratingColor,
  },
  {
    'label': 'Ayurveda & Herbs',
    'image': 'assets/categories/ayurveda&herbs.png',
    'color': AppColors.secondaryChipTextColor,
  },
  {
    'label': 'Health Food & Drinks',
    'image': 'assets/categories/health_food&drinks.png',
    'color': Colors.purpleAccent,
  },
  {
    'label': 'Fitness',
    'image': 'assets/categories/fitness.png',
    'color': Colors.pinkAccent,
  },
  {
    'label': 'Wellness',
    'image': 'assets/categories/wellness.png',
    'color': Colors.blueGrey,
  },
];

List<Map<String, dynamic>> filters = [
  {
    'label': 'Categories',
    'data': [
      "Whey Proteins",
      "Mass Gainers",
      "Pre-Workout",
      "Creatine",
      "Bottles & Shakers",
      "Amino Acids / BCAAs",
      "Multivitamins - General",
      "Peanut Butter",
      "Fish Oil",
      "Whey Protein For Beginners",
      "Weight Gainer",
      "Muesli",
      "L-Carnitine",
      "Raw Whey Proteins",
      "Gym Bags",
      "T-Shirts",
      "Whey Protein Isolate",
      "Electrolytes",
      "Ashwagandha",
      "Oats",
      "Protein Bars",
      "Pre Hormone",
      "Rice Cake",
      "Fat Burner",
      "Caps",
      "Protein Shakes",
      "EAA",
      "Glutamine",
      "ZMA",
      "Lifting Straps & Hooks",
      "Cereals",
      "Other Supports",
      "Milk Thistle",
      "Other Herbal Supplements",
      "Granola",
      "Snack / Energy Bars",
      "Citrulline Malate",
      "Protein Water",
      "L-Arginine",
      "Multivitamins - Men",
      "Multivitamins - Women",
      "CLA",
      "Gym Gloves",
      "Wrist Support",
      "Plant Proteins",
      "Tesk Kit",
      "Casein Proteins",
      "Protein For Women",
    ],
  },

  {
    'label': 'Price',
    'values': [
      [],
      [0 - 199],
      [200, 499],
      [400, 999],
      [1000, 1499],
      [1500, 1999],
      [2000, 2999],
      [3000, 4999],
      [5000, 9999],
      [10000, 9999999],
    ],
    'data': [
      "All"
          "Under ₹199",
      "₹200 - ₹499",
      "₹500 - ₹999",
      "₹1,000 - ₹1,499",
      "₹1,500 - ₹1,999",
      "₹2,000 - ₹2,999",
      "₹3,000 - ₹4,999",
      "₹5,000 - ₹9,999",
      "₹10,000 & Above",
    ],
  },
  {
    'label': 'Discount',
    'data': [
      "10% and Above",
      "20% and Above",
      "30% and Above",
      "40% and Above",
      "50% and Above",
      "60% and Above",
      "70% and Above",
      "80% and Above",
    ],
  },
  {
    'label': 'Ratings',
    'values': [null, 5, 4, 3, 2, 1, 0],
    'data': ["All", "5⭐", "4⭐", "3⭐", "2⭐", "1⭐", "Unrated Products"],
  },
];
