import 'package:ciyone_nutrimix/models/product_model.dart';
import 'package:uuid/uuid.dart';

List<ProductModel> dummyProducts = [
  ProductModel(
    id: const Uuid().v4(),
    title: 'Mb fuel one whey protein immunity+',
    subTitle: '4.4 ib chocolate',
    image: 'assets/dummy_images/image1.png',
    price: 3549,
    discount: 1550,
    rating: Rating(average: 4.5, ratings: 89, userIds: []),
  ),
  ProductModel(
    id: const Uuid().v4(),
    title: 'Healthkart hk vitals acv 750 mg effervescent',
    subTitle: ' 15 tablet(s)',
    image: 'assets/dummy_images/image2.png',
    price: 299,
    discount: 51,
    rating: Rating(average: 4.2, ratings: 34, userIds: []),
  ),
  ProductModel(
    id: const Uuid().v4(),
    title: 'Healthkart hk vitals super strength fish oil purity 84%, ',
    subTitle: '60 softgels',
    image: 'assets/dummy_images/image3.png',
    price: 599,
    discount: 400,
    rating: Rating(average: 4.5, ratings: 45, userIds: []),
  ),
  ProductModel(
    id: const Uuid().v4(),
    title: 'Muscleblaze beginner\'s protein powders',
    image: 'assets/dummy_images/image4.png',
    price: 1299,
    discount: 980,
    rating: Rating(average: 4.7, ratings: 231, userIds: []),
  ),
  ProductModel(
    id: const Uuid().v4(),
    title: 'Muscleblaze super ganiner xxl op old',
    subTitle: '6.6 ib chocolate',
    image: 'assets/dummy_images/image5.png',
    price: 2349,
    discount: 1400,
    rating: Rating(average: 4.5, ratings: 89, userIds: []),
  ),
  ProductModel(
    id: const Uuid().v4(),
    title: 'Muscleblaze super gainer XXL',
    subTitle: '11 ib chocolate',
    image: 'assets/dummy_images/image6.png',
    price: 3799,
    discount: 2700,
    rating: Rating(average: 4.5, ratings: 59, userIds: []),
  ),
  ProductModel(
    id: const Uuid().v4(),
    title: 'Muscleblaze mb-vite daily multivitamin',
    subTitle: 'Enhanced',
    image: 'assets/dummy_images/image7.png',
    price: 499,
    discount: 200,
    rating: Rating(average: 4.6, ratings: 89, userIds: []),
  ),
  ProductModel(
    id: const Uuid().v4(),
    title: 'Muscleblaze pre workout 200 xtreme',
    subTitle: '0.22 ib fruit',
    image: 'assets/dummy_images/image8.png',
    price: 549,
    discount: 200,
    rating: Rating(average: 4.3, ratings: 38, userIds: []),
  ),
  ProductModel(
    id: const Uuid().v4(),
    title: 'Muscleblaze raw whey protein powders',
    subTitle: '2.2 ib . unflavoured',
    image: 'assets/dummy_images/image9.png',
    price: 1999,
    discount: 0,
    rating: Rating(average: 4.8, ratings: 209, userIds: []),
  ),
  ProductModel(
    id: const Uuid().v4(),
    title: 'Muscleblaze super gainer xxl powder',
    subTitle: '11 ib . chocolate',
    image: 'assets/dummy_images/image10.png',
    price: 3449,
    discount: 3000,
    rating: Rating(average: 4.0, ratings: 45, userIds: []),
  ),
  ProductModel(
    id: const Uuid().v4(),
    title: 'Healthkart hk biotin (10000 mcg) tablets',
    subTitle: 'Unflavoured . 90 tablet(s)',
    image: 'assets/dummy_images/image11.png',
    price: 449,
    discount: 551,
    rating: Rating(average: 5, ratings: 489, userIds: []),
  ),
  ProductModel(
    id: const Uuid().v4(),
    title: 'Healthkart hk vitals super strength fish oil purity 84%, ',
    subTitle: '60 Softgels',
    image: 'assets/dummy_images/image12.png',
    price: 599,
    discount: 400,
    rating: Rating(average: 4.5, ratings: 23, userIds: []),
  ),
];
